kind = "web"
previewPath = "/"
title = "Cydestore"
version = "1.0.0"
id = "artifacts/electronics-store"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19108

[services.development]
run = "pnpm --filter @workspace/electronics-store run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/electronics-store", "run", "build" ]
publicDir = "artifacts/electronics-store/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19108"
BASE_PATH = "/"
